# Generated by Django 5.0.6 on 2025-04-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('jobRole', models.CharField(max_length=20)),
                ('hireDate', models.DateField()),
                ('securityQuestion_Answer1', models.CharField(max_length=100)),
                ('securityQuestion_Answer2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department_Leader',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('jobRole', models.CharField(max_length=20)),
                ('hireDate', models.DateField()),
                ('securityQuestion_Answer1', models.CharField(max_length=100)),
                ('securityQuestion_Answer2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Engineer',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckCard',
            fields=[
                ('cardId', models.AutoField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=50)),
                ('redColorDescrip', models.CharField(max_length=255)),
                ('greenColorDescrip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HealthCheck_Card',
            },
        ),
        migrations.CreateModel(
            name='ResultView',
            fields=[
                ('resultId', models.AutoField(primary_key=True, serialize=False)),
                ('summaryType', models.CharField(max_length=50)),
                ('averageProgressScore', models.IntegerField()),
                ('progressOverTime', models.IntegerField()),
                ('cardProgressSummary', models.CharField(max_length=500)),
                ('teamProgressSummary', models.CharField(max_length=500)),
                ('deptProgressSummary', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Result_View',
            },
        ),
        migrations.CreateModel(
            name='SeniorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('jobRole', models.CharField(max_length=20)),
                ('hireDate', models.DateField()),
                ('securityQuestion_Answer1', models.CharField(max_length=100)),
                ('securityQuestion_Answer2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Senior_Manager',
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('jobRole', models.CharField(max_length=20)),
                ('hireDate', models.DateField()),
                ('securityQuestion_Answer1', models.CharField(max_length=100)),
                ('securityQuestion_Answer2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Team_Leader',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50, unique=True)),
                ('numOfTeams', models.IntegerField()),
                ('deptCreateDate', models.DateField()),
                ('departmentLocation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.departmentleader')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('sessionDate', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.engineer')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20, unique=True)),
                ('numOfMembers', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('voteColour', models.CharField(max_length=10)),
                ('progressIndicator', models.CharField(max_length=20)),
                ('voteComment', models.CharField(max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.session')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.healthcheckcard')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.resultview')),
            ],
            options={
                'db_table': 'HealthCheck_Result',
                'unique_together': {('card', 'result')},
            },
        ),
        migrations.CreateModel(
            name='HealthCheckVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCompleted', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.healthcheckcard')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vote')),
            ],
            options={
                'db_table': 'HealthCheck_Vote',
                'unique_together': {('vote', 'card', 'dateCompleted')},
            },
        ),
    ]
