# Generated by Django 5.0.6 on 2025-04-30 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckCard',
            fields=[
                ('cardId', models.AutoField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=50)),
                ('redColorDescrip', models.CharField(max_length=255)),
                ('greenColorDescrip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HealthCheck_Card',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50, unique=True)),
                ('numOfTeams', models.IntegerField()),
                ('deptCreateDate', models.DateField()),
                ('departmentLocation', models.CharField(max_length=50)),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('sessionDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20, unique=True)),
                ('numOfMembers', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='database.department')),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hireDate', models.DateField()),
                ('securityQuestion_Answer1', models.CharField(max_length=100)),
                ('securityQuestion_Answer2', models.CharField(max_length=100)),
                ('is_engineer', models.BooleanField(default=False)),
                ('is_team_leader', models.BooleanField(default=False)),
                ('is_department_leader', models.BooleanField(default=False)),
                ('is_senior_manager', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='database.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('voteColour', models.CharField(max_length=10)),
                ('progressIndicator', models.CharField(max_length=20)),
                ('voteComment', models.CharField(max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.session')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCompleted', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.healthcheckcard')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.team')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vote')),
            ],
            options={
                'db_table': 'HealthCheck_Vote',
                'unique_together': {('vote', 'card', 'dateCompleted')},
            },
        ),
    ]
