# Generated by Django 5.0.6 on 2025-04-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jobRole',
        ),
    ]
