# Generated by Django 5.0.6 on 2025-04-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_department', to='database.departmentleader'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineers', to='database.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to='database.teamleader'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='database.department'),
        ),
    ]
