# Generated by Django 5.0.6 on 2025-04-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_department_user_department_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckvote',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.department'),
        ),
        migrations.AddField(
            model_name='healthcheckvote',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.team'),
        ),
    ]
