# Generated by Django 5.0.6 on 2025-04-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_userprofile_jobrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCheckResult',
        ),
        migrations.DeleteModel(
            name='ResultView',
        ),
    ]
